project:
  type: website
  output-dir: _site

website:
  title: "Tech Blog"
  description: "Notes on challenging technical things"
  navbar:
    right:
      - icon: sun
        id: quarto-color-scheme-toggle
  search: true

format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark:  [darkly, custom.scss]
    highlight-style: github
    code-fold: false
    code-tools: false
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    number-sections: false
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    fig-responsive: true
    html-math-method: katex

execute:
  freeze: auto
  echo: true
  warning: false
